### ISSUE TITLE
Standalone SQLAlchemy Relationships don't work

### ISSUE THREAD

**Issue by vpassapera** [briancappello/py-yaml-fixtures#1]
I have a very simple DB with just 3 entities and relationships between them, following the directions for relationships in the doc, I am getting some errors when trying to load fixtures. I was able to get past some of the errors by fixing some of the code in the library itself, however, running into more issues I decided that without test coverage at this time this lib may be too young.

Please add tests to ensure the documentation is accurate.

Thank you.

**Comment by briancappello** [comment]
Hey, I'm sorry you ran into trouble, you're right that it's still a very
young library!

Can you share some more details about what errors you got and maybe I can
try to help figure out what's going wrong? If there are bugs I'd like to
fix them :)

**Comment by briancappello** [comment]
This should be fixed as of `v0.5.0`

Please feel free to re-open with more details if you still run into trouble!
