### ISSUE TITLE
PyPI sdist file name has spaces in it

### ISSUE THREAD

**Issue by warsaw** [briancappello/py-yaml-fixtures#2]
The sdist tarball on PyPI has spaces in its name.  That makes it problematic to download and install using anything other than pip.

**Comment by briancappello** [comment]
Ah good catch, thanks! I just made a new release with that hopefully fixed... dunno how PyPI feels about "changing" the name of a project tho - can you by chance verify if it worked for your tools?

**Comment by warsaw** [comment]
Wow, thanks for the quick fix!  Confirmed that it works now.
