### ISSUE TITLE
feature for SqlAlchemy - include relationships in filters

### ISSUE THREAD

**Issue by westonplatter** [briancappello/py-yaml-fixtures#4]
@briancappello following on the tails of #3, it would be great to filter by `relationships` in addition to model attributes, here https://github.com/briancappello/py-yaml-fixtures/blob/master/py_yaml_fixtures/factories/sqlalchemy.py#L71

**Comment by briancappello** [comment]
Definitely, that's a great idea! I've had some bugs with relationships in the past in this library so hopefully I can come up with something. About to go on vacation though so it might be a second before I can get to it :/

**Comment by westonplatter** [comment]
@briancappello totally understand. Hope the vacation is refreshing!! I found a work around that solves my issue so not a pressing need. If this becomes a pertinent need, I can add it. Thanks for paving the way with what's already there.

**Comment by briancappello** [comment]
Thanks!! I'd be curious to see what you were able to come up with, if it's something shareable at least :)

**Comment by briancappello** [comment]
Hey @westonplatter, just pushed up https://github.com/briancappello/py-yaml-fixtures/pull/5 - can you try that out and see if it works for you? If not, could you share something I can try to reproduce this issue with? Thanks!

**Comment by westonplatter** [comment]
@briancappello hey, thanks a ton for sketching up a solution. I'll try it out later today.

**Comment by briancappello** [comment]
Cool. It's been a little while since I've run this code, definitely remember there being issues with specifying many-to-many fixtures. If I recall correctly you have to specify the relationships on the join table model side? But anyways, please do report any other challenges you come across and I'll do my best to get them sorted!

**Comment by briancappello** [comment]
@westonplatter hey, just following up - did PR #5 work for you?

**Comment by westonplatter** [comment]
@briancappello almost. Sqlalchemy expects to have referencing model's primary id set. 

For example, 
```bash
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't resolve value for column parent_model.id on object <ParentModel at 0x12a603150>; no value has been set for this column
[SQL: SELECT child_model.id AS child_model_id, child_model.name AS child_model_name, child_model.parent_model_id AS child_model_parent_model_id, child_model.source_published_timestamp AS child_model_source_published_timestamp 
FROM child_model 
WHERE child_model.name = %(name_1)s AND child_model.source_published_timestamp = %(source_published_timestamp_1)s AND %(param_1)s = child_model.source_document_id]
```

I was able to adjust code from your pull request to get it to work,

```
# bottom part of SQLAlchemyModelFactory._get_existing
filter_expressions = []
  for k, v in filter_kwargs.items():
    filter_expressions.append(getattr(model_class, k) == v)

    if k in relationships:
      for pk in v.__mapper__.primary_key:
        pk_value = getattr(v, pk.name)
          if pk_value is None:
            return None

return self.session.query(model_class).filter(*filter_expressions).one_or_none()
```

Curious to get your take on the changes to see if it's a good final solution.

**Comment by briancappello** [comment]
@westonplatter 

I incorporated your suggested fix into #5, and it doesn't seem to break anything on my end, but, I'm also not able to figure out how to make your added code path get hit... So I guess I'd like to better understand the bug you're encountering.

Are you using this lib with just SQLAlchemy, with Flask SQLAlchemy, or with Flask Unchained? Can you share the model classes and YAML fixture file(s) you're able to raise the error with?

Thanks!

**Comment by westonplatter** [comment]
@briancappello I'm using SQLAlchemy without flask.

Model classes as follows,
```
class Parent(Base):
    __tablename__ = "parent"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(VARCHAR(100), nullable=False, unique=True)
    address = Column(VARCHAR(100), nullable=False, unique=True)
    description = Column(Text, nullable=True)

    children = relationship("Children", back_populates="parent")
    other_model = relationship(
        "OtherModel", back_populates="source_document"
    )


class Child(Base):
    __tablename__ = "child"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(VARCHAR(100), nullable=False, unique=False)
    parent_id = Column(Integer, ForeignKey("parent.id"))
    parent = relationship("Parent", back_populates="children")
    source_published_timestamp = Column(DateTime, nullable=False)
    Index(
        "parent_per_source_uniq",
        parent_id,
        source_published_timestamp,
        unique=True,
    )
```

The code I added gets run when child record checks to see if a parent object exists. Because the parent's `id` is None (hasn't been saved to the DB), the SQL to lookup the parent errors out since the id isn't added to the sql statement. At least, that's my interpretation of what's going on.

@briancappello thanks for working through the details on this.

**Comment by briancappello** [comment]
@westonplatter Awesome, thanks! I was able to reproduce, and added a test as well.

**Comment by westonplatter** [comment]
@briancappello score. Thanks!
