### ISSUE TITLE
Hashing passwords for user fixture

### ISSUE THREAD

**Issue by KrzysztofWelc** [briancappello/py-yaml-fixtures#8]
I'm trying to populate my database with fake users. When i run my fixtures all data from yaml files gets inserted to db in unchanged form, despite the fact, that User model's ```__init__``` method takes password argument, and sets ```self.password``` to password hash. Is there any way to get this working?

**Comment by briancappello** [comment]
Hey, thanks for the report! I'm assuming you're using SQLAlchemy? The challenge is that upon model _creation_, the `__init__` method is called, while upon _update_, direct attribute setters are used. And in fact, if you don't override the default `__init__` method, the default implementation from SQLAlchemy also uses attribute setters. Therefore, the solution is to use properties:

```python
from sqlalchemy.ext.hybrid import hybrid_property

class User(BaseModel):
  _password = Column('password', String)

  @hybrid_property
  def password(self):
    return self._password

  @password.setter
  def password(self, plaintext):
    self._password = hash_password(plaintext)
```

This way, when you say `user_instance.password = "plaintext-password-value"`, the plaintext password will be automatically hashed, while upon retrieving the value using `user.password`, you always get the hashed value.

**Comment by KrzysztofWelc** [comment]
Works, thank u ;)

**Comment by lekhnath** [comment]
Password hashing is not working for Django user models either.
